package de.debuglevel.walkingdinner.rest.dietcompatibility

import de.debuglevel.walkingdinner.rest.Meeting
import de.debuglevel.walkingdinner.rest.participant.*
import java.util.stream.Stream

object TestDataCourseCompatibility {
    fun compatibleMeetingsProvider() = Stream.of(
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(CookingCapability.OmnivorVorspeise),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Vorspeise"
            )
        ),
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(CookingCapability.VeganHauptgericht),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Hauptspeise"
            )
        ), MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(CookingCapability.VeganDessert),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Dessert"
            )
        )
    )

    fun incompatibleMeetingsProvider() = Stream.of(
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(CookingCapability.VegetarischVorspeise),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Vorspeise"
            )
        ),
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(CookingCapability.OmnivorHauptgericht, CookingCapability.VegetarischHauptgericht),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Hauptspeise"
            )
        ), MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(CookingCapability.VegetarischDessert),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Dessert"
            )
        )
    )

    data class MeetingData(
        val meeting: Meeting
    )
}