package de.debuglevel.walkingdinner.rest.dietcompatibility

import de.debuglevel.walkingdinner.rest.Meeting
import de.debuglevel.walkingdinner.rest.participant.*
import java.util.stream.Stream

object TestDataCourseCompatibility {
    fun compatibleMeetingsProvider() = Stream.of(
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(CookingCapability.OmnivoreAppetizer),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Vorspeise"
            )
        ),
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(CookingCapability.VeganMaindish),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarian,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Hauptspeise"
            )
        ), MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarian,
                        listOf(CookingCapability.VeganDessert),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Dessert"
            )
        )
    )

    fun incompatibleMeetingsProvider() = Stream.of(
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarian,
                        listOf(CookingCapability.VegetarianAppetizer),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Vorspeise"
            )
        ),
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(CookingCapability.OmnivoreMaindish, CookingCapability.VegetarianMaindish),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarian,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Hauptspeise"
            )
        ), MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(CookingCapability.VegetarianDessert),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "Dessert"
            )
        )
    )

    data class MeetingData(
        val meeting: Meeting
    )
}