package de.debuglevel.walkingdinner.rest.plan.dietcompatibility

import de.debuglevel.walkingdinner.rest.Meeting
import de.debuglevel.walkingdinner.rest.participant.*
import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.TestInstance
import org.junit.jupiter.params.ParameterizedTest
import org.junit.jupiter.params.provider.MethodSource
import java.util.stream.Stream

@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class HardCompatibilityTests {

    @ParameterizedTest
    @MethodSource("compatibleMeetingsProvider")
    fun `meetings are compatible`(testData: MeetingData) {
        // Arrange

        // Act
        val areCompatible = HardCompatibility.areCompatibleTeams(testData.meeting)

        // Assert
        assertThat(areCompatible).isTrue()
    }

    @ParameterizedTest
    @MethodSource("incompatibleMeetingsProvider")
    fun `meetings are incompatible`(testData: MeetingData) {
        // Arrange

        // Act
        val areCompatible = HardCompatibility.areCompatibleTeams(testData.meeting)

        // Assert
        assertThat(areCompatible).isFalse()
    }

    fun compatibleMeetingsProvider() = Stream.of(
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "course"
            )
        ),
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "course"
            )
        ), MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "course"
            )
        )
    )

    fun incompatibleMeetingsProvider() = Stream.of(
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "course"
            )
        ),
        MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegetarisch,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "course"
            )
        ), MeetingData(
            Meeting(
                listOf(
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Omnivore,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    ),
                    Team(
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        Cook(
                            Name(
                                "cook"
                            ),
                            MailAddress("mail"),
                            PhoneNumber("123")
                        ),
                        "address",
                        Diet.Vegan,
                        listOf(),
                        null,
                        null,
                        "city"
                    )
                ),
                "course"
            )
        )
    )

    data class MeetingData(
        val meeting: Meeting
    )
}